services:
  - type: web
    name: FoodDelivery-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    routes:
      # 🔥 This rewrite fixes React Router DOM 404 on refresh
      - type: rewrite
        source: /*
        destination: /index.html
