services:
  - type: web
    name: food-delivery-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
