services:
  - type: web
    name: admin
    env: static
    staticPublishPath: build
    buildCommand: npm run build
    redirects:
      - source: /*
        destination: /index.html
        status: 200
